### ISSUE TITLE
Questions about the data

### ISSUE THREAD

**Issue by xiehuanyi** [HKUDS/DCCF#10]
Hi, what's the meaning of the data in the train.pkl and train_index.pkl? If I have some data like (users, items, ratings). Can I directly convert them into the format needed for the DCCF model? 
Looking forward to your reply!

**Comment by Re-bin** [comment]
Hi 👋

Thanks for your interest! The `train.pkl` file contains the training data, which is represented as a zero-one sparse matrix in COO format. It has a shape of `[n_user, n_item]`, where a value of 1 indicates an interaction between a user and an item. For example, if the entry at the 6th row and 5th column is 1, it represents a recorded interaction between user 6 and item 5.

However, in certain environments, reading the `train.pkl` file can be challenging. To address this, I have directly stored the coordinates of the entries with a value of 1 in the `train_index.pkl` file. This file is a numpy array with a shape of `[2, n_interactions]`. The first row contains the user IDs, the second row contains the item IDs, and each column represents an interaction.

For your data consisting of (users, items, ratings), you can easily convert it into the required format for the DCCF model 😊. The only thing you need to consider is the **ratings**, as in Collaborative Filtering, the interactions are typically represented by either 0 or 1. Basically, you should filter out the low-rating interactions and consider all remaining interactions as the same (recorded as 1 in the matrix).

I hope the above answers can help with your confusion.

Best regards,
Xubin

**Comment by xiehuanyi** [comment]
Thanks for your quick response!

I followed your instruction and successfully run the code on some other datasets like `yelp` , `tripadvisor` and `moviesandtv`. However, when I tried a subset of `amazon`, I got the following dict key error. I used the same script to convert the data format and these dataset share the same format so I think it should work as well. 

I wonder if it's possible that I can skip such samples or there are any other better solutions. 

Here is the detailed error information:
```
(rec_sys) root@iZuf6ggnpq6yjcn64csom2Z:~/work/codes/DCCF# python DCCF_PyTorch.py --dataset ClothingShoesAndJewelry --epoch 100
Try an alternative way of reading the data.
n_users=38764, n_items=22919
n_interactions=179223
n_train=143378, n_test=35845, sparsity=0.00016
************************* Run with following settings 🏃 ***************************
Namespace(Ks='[20, 40]', batch_size=10240, cen_reg=0.005, data_path='data/', dataset='ClothingShoesAndJewelry', emb_reg=2.5e-05, embed_size=32, epoch=100, lr=0.001, n_batch=40, n_intents=128, n_layers=2, sample_num=40, save_model=False, seed=2022, show_step=1, ssl_reg=0.1, temp=1, train_num=10000, verbose=1)
************************************************************************************
already create adjacency matrix (61683, 61683) 0.16083550453186035
Start Training
Traceback (most recent call last):
  File "DCCF_PyTorch.py", line 91, in <module>
    n_samples = data_generator.uniform_sample()
  File "/root/work/codes/DCCF/utility/load_data.py", line 82, in uniform_sample
    pos_for_user = self.train_items[user]
KeyError: 16085
```

**Comment by xiehuanyi** [comment]
I tried to fix this by editing the source code. I change these lines of codes.

First in the load_data.py, I edited the uniform_sample() function to make sure the user exists in the train_items's keys.
```
    def uniform_sample(self):
        # users = np.random.randint(0, self.n_users, int(self.n_batch * self.batch_size))
        users = []
        while len(users) <= int(self.batch_size * self.n_batch):
            user = random.randint(0, self.n_users - 1)
            if user in self.train_items:
                users.append(user)
        users = np.array(users)
```
Second, in the batch_test.py, I changed the eval_PyTorch(). I checked if the user_batch[i] in the train_items's keys. If not, I assign it a empty list.

```
for i in range(len(user_batch)):
            train_items = list(data_generator.train_items[user_batch[i]]) if user_batch[i] in data_generator.train_items else []
            exclude_index.extend([i] * len(train_items))
            exclude_items.extend(train_items)
            ground_truth.append(list(data_generator.test_set[user_batch[i]]))
```

By these changes, I can only make sure it runs fine but do not guanrantee the correctness of the results. I am new to recommendation system, and I do need your help to make sure if these edition is correct.
