### ISSUE TITLE
Request for datasets

### ISSUE THREAD

**Issue by BlueGhostZ** [HKUDS/DCCF#11]
Hi author, is it possible to provide the mapping file between the dataset you used and the original dataset?

**Comment by Re-bin** [comment]
Hi 👋

Thank you for your interest! We utilized the datasets processed by [HCCF](https://github.com/akaxlh/HCCF/tree/main) and [SHT](https://github.com/akaxlh/SHT). Mapping files were not generated during the data processing. However, you can refer to this [link](https://github.com/akaxlh/HCCF/tree/main/Data%20Processing) to access the data processing codes in HCCF (including the codes for Amazon-book data). These codes may be helpful to you :)

Best regards,
Xubin
