### ISSUE TITLE
关于DGCF,DGCL模型的复现

### ISSUE THREAD

**Issue by cutefishh** [HKUDS/DCCF#14]
作者您好！请问一下在4.2节性能比较中，模型DGCF和DGCL是怎么复现的呢？是否有代码可以参考

**Comment by Re-bin** [comment]
嗨 👋！

感谢关注！以下是一些信息可以帮助您实现DGCF和DGCL:
- DGCF模型是直接参考其[原始代码](https://github.com/xiangwang1223/disentangled_graph_collaborative_filtering)，并且转换成pytorch形式，而后在和DCCF同样的代码框架下测试的；
- DGCL模型是直接参考其[原始论文](https://proceedings.neurips.cc/paper_files/paper/2021/file/b6cda17abb967ed28ec9610137aa45f7-Paper.pdf)，使用了LightGCN来获得node embedding，augmentation用的是edge dropout。

希望上述回答可以帮到您 :)

Best regards,
Xubin

**Comment by cutefishh** [comment]
好的谢谢！
