### ISSUE TITLE
model problem

### ISSUE THREAD

**Issue by kbk12** [HKUDS/DCCF#3]
您好，在跑这篇论文模型时，遇到OSError: /home/XXXX/.conda/envs/py381/lib/python3.8/site-packages/torch_sparse/_diag_cuda.so: undefined symbol: _ZN3c106detail19maybe_wrap_dim_slowEllb问题，可以说一下怎么解决吗，万分感谢

**Comment by Re-bin** [comment]
嗨，感谢关注！

这个可能是由于torch_sparse安装失败导致的，您可以通过以下方式卸载torch_sparse，
```shell
pip uninstall torch-sparse
```
然后重新安装torch_sparse，我的版本为0.6.14。

希望能解决您的问题。

Best,
Xubin
