### ISSUE TITLE
公式

### ISSUE THREAD

**Issue by yuanzhongfei** [HKUDS/DCCF#4]
请问论文中公式（1）如何理解呢，不太懂P(y,cu,cv|u,v)表示什么意思,以及公式(2)的推导？谢谢

**Comment by Re-bin** [comment]
你好，感谢关注！

1. p(y,cu,cv|u,v)是指代明确具体意图（cu和cv）情况下的分布。考虑到p(y|u,v)是p(y,cu,cv|u,v)的边缘分布，并且边缘分布是通过对特定变量积分而得。所以公式（1）就是将p(y|u,v)转写成积分形式，从而引入了意图变量（cu和cv）。
2. 公式（2）的推导存在一个因果关系假设前提，即u决定cu，v决定cv，cu和cv决定y，因此可以将p(y,cu,cv|u,v)进行拆分。

希望能解决您的问题。

Best,
Xubin

**Comment by yuanzhongfei** [comment]
好的 谢谢
