### ISSUE TITLE
求教模型分析中  公式21 22 的理解

### ISSUE THREAD

**Issue by MrShouxingMa** [HKUDS/DCCF#7]
非常荣幸能够拜读您的文章，文章巧妙的将理论假设，数学推导和代码实现结合，并用实验证明的idea的有效性。
在详细阅读文章的模型分析部分时，遇到一些疑惑，还请不吝赐教：

1. 代码中可以看到用户项目意图矩阵是一个32 x 128的矩阵，公式21为对某个用户意图的the disentangled global collaborative view进行求导，想请问这里矩阵是不是一个K=32,d=128的矩阵？论文描述里面是否混用了参数d？
2. 请问公式22中的m和n是代表不同的用户吗，还是其他含义？
3. 请问古罗马I是一个判别函数？
4. 感觉公式22同时使用了复合函数求导和函数乘积的求导法则，但并没有看懂，请问可否给出详细推导过程？

祝好！

**Comment by Re-bin** [comment]
嗨，您好！

感谢您的关注和认可！以下是关于疑惑的解答：
1. 关于问题1，公式21是向量r对向量c求导，这两个向量都是维度为d，因此求导之后是一个 [d, d] 的矩阵。代码中的创建的 [32, 128] 矩阵是意图矩阵的转置形式；
2. 关于问题2，m/n分别用于指代r和c这个向量中的第m/n个位置的元素（实数）；
3. 关于问题3，是判别函数，当m=n时为1；
4. 关于问题4，这一步的求导是元素对元素求导，r_m是关于c_n的一个函数（为了方便，省略了部分上下标），基于此就可以求出结果，其核心是求导结果前面的P_t，后面的式子是推导结果的副产物，可不必过多分析。

希望上述解答可以回答您的疑惑 :)

Best regards,
Xubin

**Comment by MrShouxingMa** [comment]
明白了，非常感谢您抽出宝贵时间来的耐心回复 ^_^

祝好！
