### ISSUE TITLE
model problem

### ISSUE THREAD

**Issue by Pursuerwener** [HKUDS/DCCF#8]
when i run python DCCF_PyTorch.py --dataset gowalla --epoch 150
get this error 
file"DCCF_PyTorch.py",line 53, in <module>
data_generator = Data(args)
file"DCCF-main\utility\load_data.py" line19, in __init__
train_mat = pickle.load(f)

ModuleNotFoundError:No module named 'scipy.sparse._coo'

i have installed the pack in your readme.md

**Comment by Re-bin** [comment]
Hello, thank you for your attention!

Please try updating to **scipy==1.9.1**. Based on my testing, it is feasible to read `train.pkl` in this scenario with the mentioned version.

I hope the above answers can help with your confusion : )

Best regards,
Xubin

**Comment by Pursuerwener** [comment]
Thank you very much for your reply，I have reinstalled the corresponding package you mentioned,

numpy == 1.22.3
pytorch == 1.11.0 (GPU version)
torch-scatter == 2.0.9
torch-sparse == 0.6.14
scipy == 1.9.3

but it still runs with this issue. I have not found a solution to this problem from elsewhere,I don't know where the problem lies

**Comment by Re-bin** [comment]
Hi!

It appears that the issue might be related to the `scipy`. However, it seems that the version 1.9.3 works fine. Have you considered checking the version of scipy in your environment using the `pip list` command? 

Alternatively, you could try installing the latest version of scipy directly to see if that resolves the problem.

Best regards,
Xubin

**Comment by Pursuerwener** [comment]
update latest scipy is no effect
I wrote a piece of code trying to open the test.pkl 

import pickle
F = open(r'E:\DCCF-main\data\amazon\test.pkl','rb')
content=pickle.load(F)
print(content)

run this code,get the same error
ModuleNotFoundError:No module named 'scipy.sparse._coo'

i find this'scipy.sparse._coo' in line 1 of test.pkl

Is it a problem with data or is it necessary to process the data

**Comment by Re-bin** [comment]
Hi,

It appears that the data is intact and free of any issues. I have re-downloaded the repository and attempted to read it, yielding the following results : )

![image](https://github.com/HKUDS/DCCF/assets/52506698/c76b9db7-ca19-4813-b285-e8087f04e221)

The situation is a bit peculiar. Have you tried creating a new Python virtual environment on your own computer? 
Alternatively, you could attempt accessing the file on a different computer.

Best regards,
Xubin

**Comment by Pursuerwener** [comment]
Thank you very much for your help. I am using pycharm, so I will reconfigure the environment and try again
